"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PhoneBook.py']
DATA_FILES = [('',['images']),('',['PhoneBook.db']),('',['RadioButtonClass.py'])]
OPTIONS = {'iconfile':'phonebook.icns',
                   'includes': ['sip', 'PyQt5']} #'argv_emulation': True

setup(
    app=APP,
    version='0.0',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
